name: Update Starlink

on:
  schedule:
    - cron: "17 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Descargar datos Starlink
        run: |
          curl -L "https://celestrak.org/NORAD/elements/gp.php?GROUP=starlink&FORMAT=JSON" -o starlink/starlink.json

      - name: Commit cambios
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add starlink/starlink.json
          git commit -m "update starlink data" || echo "sin cambios"
          git push
